### ISSUE TITLE
Your domain expired...

### ISSUE THREAD

**Issue by WebShapedBiz** [needle-and-thread/birdie#186]
... and seeing that your latest "daily" build is 6 months old, I must ask the question - is this project still alive? It was the best desktop Twitter client I've ever used but it seems that it was abandoned now for the second time in the last few years, but nobody has informed the user community.
How hard is to fix not working URL links? If that cannot be resolved within 6 months, I'm afraid to ask for the app starting failure and all other issues.

I hope we will hear from devs soon with some kind of Birdie status explanation. Is there a hope for Birdie or should we start looking elsewhere for the desktop Twitter client?

Cheers.

**Comment by nathandyer** [comment]
Hi! Yes, the project is still very much alive. The URL links bug was fixed [at the end of may](https://github.com/birdieapp/birdie/commit/7003d5be76819536de3b27b73a996ea9c670f368). Development has slowed a bit because of personal commitments in recent months (moving, classwork, etc.), but we're still working on Birdie and will be releasing version 2.0 soon. Development time should greatly increase here in the coming weeks and months.

As for the expired domain, we are aware, and are actively in the process of moving our project page to a new domain (and a new site, for that matter). We'll have more news about this very soon.

I'm going to leave this issue open until we get our domain switched over. Cheers! :-)

**Comment by WebShapedBiz** [comment]
Thank you for your time and effort, love your work.

Cheers.
